### ISSUE TITLE
[要望]曲データのbase64埋め込み

### ISSUE THREAD

**Issue by azarakko** [cwtickle/danoniplus#139]
**背景**
html版ダンオニについて現状mp3を直接読み込んでいますが、
その関係上mp3ファイルを直接ファイルサーバーにアップロードする必要があります。
作曲者の規約によってはmp3を直接ファイルサーバーへアップロードすることがNGと示されていることがあり、可能であればmp3ファイルを直接配置しない方法があるとうれしいです。

**解決方法**
現状audioファイルをmp3ファイルのファイルパスとして埋め込んでいますが、代わりにテキストとして、jsあるいはhtmlに埋め込むdatauriによる指定方法があります

https://developer.mozilla.org/ja/docs/data_URIs

以上の方法で以下のようなuri(datauriによりエンコードされた文字列）

data:audio/mp3;base64,base64符号化されたmp3データ

を

g_audio.src= "data:audio/mp3;base64,base64符号化されたmp3データ"

のように渡せるように出来るようにしたうえでdatauriのデータをhtml/js/外部テキストのいずれかとして渡せるように出来れば音楽ファイルのサイズは増加しますが、作曲者の規約の問題を回避できると思います。

**Comment by cwtickle** [comment]
ご意見ありがとうございます。
こんな指定の仕方があるのは知りませんでした。。。

試行錯誤しましたが、試しにbase64エンコードしたデータを使って試してみました。
http://cw7.sakura.ne.jp/danoni/2013/0079_Thrustup-test.html

上記はmp3ファイルそのものではなく、エンコードしたデータをjsデータに貼って動かしています。
この場合「0079_Thrustup.js」というのがそれで、中身はこうなっています。
```
function musicInit(){
  g_musicdata='base64エンコードされた音楽データ';
}
```
大きな問題が無ければ、このバージョンをリリースする方向で動いてみます。
（当面、互換性のためmp3ファイル読込も継続する予定です）

**Comment by azarakko** [comment]
確認実装等ありがとうございます。

> 大きな問題が無ければ、このバージョンをリリースする方向で動いてみます。
>（当面、互換性のためmp3ファイル読込も継続する予定です）

mp3ファイルを直接置いた方が基本的に扱いが楽と思いますので、オプション的な位置として実装していただければ幸いです。

**Comment by cwtickle** [comment]
ver1.7.1にて実装しましたので、クローズします。
