### ISSUE TITLE
[バグ] difDataで指定したノルマ率が反映されない

### ISSUE THREAD

**Issue by prlg25** [cwtickle/danoniplus#1574]
## 不具合内容 / The Problem

- difDataに次のように70%以外のノルマを指定しても反映されず、70%のノルマが指定されてしまいます。
- |difData=12,Normal,3,80,2,7|

## スクリーンショット / Screenshot
![image](https://github.com/cwtickle/danoniplus/assets/99570135/ab0968ab-1089-43ae-a7a4-b7f5037d79bc)
![image](https://github.com/cwtickle/danoniplus/assets/99570135/b260860f-ff1d-4321-bfe8-1c1dd62d9f8e)

## 期待する見せ方・挙動 / Expected Behavior

- difDataで指定したノルマ（例の場合80％)が指定される。

## 不具合内容の再現手段 / Steps to Reproduce

- difDataに70%以外のノルマ率を指定する。
ex: |difData=12,Normal,3,80,2,7|
- 以下の作品で発生しています。
  - https://prologues.works/fevereiro/
    - Psyched fevereiroのVH、EXのノルマが80想定なのが、ノルマ70になっている。
  - 青春ナイフのMildがノルマ70になっている。（ソースを見ると50想定のはず）
    - https://cw7.sakura.ne.jp/danoni/2023/0356_SeishunKnife.html
- 以下のような記述をしている作品は、想定通り動いています。
  - |gaugeNormal=70,2,7$70,2,10$80,2,14|
    - https://prologues.works/lp6/
## 動作環境・ブラウザ / Environment

- Version: 33.1.1, 34.2.0
- Windows 
- Vivaldi

※ ver32は大丈夫みたいです。(下記作品は指定通りのノルマ率となっている)
- https://vorhandensein.sakura.ne.jp/danoni/342_kirakira/
## その他検討事項 / Other Considerations

-

**Comment by cwtickle** [comment]
報告ありがとうございます。
ver32.6.0以降で発生することを確認しました。

参考）全バージョンのプレビューサイト
https://danonicw.skr.jp/

#1509 で混入したと思われますが、この時点で機能追加やコードリファクタリングを行っているため、簡単に直らないかもしれません。

**Comment by cwtickle** [comment]
この辺の仕様がややこしいので一旦整理します。

### 1. ゲージ優先度
- カスタムゲージの場合
    - ゲージ個別設定(gaugeXXX) > 共通設定(g_presetObj.gaugeCustom)
- 汎用ゲージかつゲージ初期設定(Original or Normal)で無い場合
    - ゲージ個別設定(gaugeXXX) > 共通設定(g_presetObj.gaugeCustom) > 基本設定(g_gaugeOptionObj)
- 汎用ゲージかつゲージ初期設定(Original or Normal)の場合
    - ゲージ個別設定(gaugeXXX) > 共通設定(g_presetObj.gaugeCustom) > 譜面ヘッダー(difData) > 基本設定(g_gaugeOptionObj)

### 2. ゲージ設定を変更した場合の挙動
- Difficultyを変更した場合
    - 同一のゲージ設定名があれば、そのゲージ設定に合致するゲージ設定を1.から取得
    - ない場合は、その譜面のゲージ設定群の先頭をゲージ設定として、そのゲージ設定を1.から取得
- Gaugeを変更した場合
    - 対象譜面のゲージ設定群のカーソルを1つ右 or 左にずらして、そのゲージ設定を1.から取得

### 3. ゲージ設定関連の変数（ノルマ、回復、ダメージ、初期値）
- ゲージ個別設定(gaugeXXX)、共通設定(g_presetObj.gaugeCustom)
⇒ g_gaugeOptionObj.gaugeXXXs = { lifeBorders: [], lifeRecoverys: [], lifeDamages: [], lifeInits: []  }
- 譜面ヘッダー(difData)
⇒ g_headerObj = { lifeBorders: [], lifeRecoverys: [], lifeDamages: [], lifeInits: []  }
　※g_headerObjは譜面ヘッダー定義の集合体のため、ゲージ設定のみ抜粋
- 基本設定(g_gaugeOptionObj)
    - ライフ制ゲージの場合
    ⇒ g_gaugeOptionObj = { clearSurvival: [], rcvSurvival: [], dmgSurvival: [], initSurvival: [] }
    - ノルマ制ゲージの場合
    ⇒ g_gaugeOptionObj = { clearBorder: [], rcvBorder: [], dmgBorder: [], initBorder: [] }

### 4. ノルマ制ゲージ決定条件
- ゲージ個別設定(gaugeXXX)、共通設定(g_presetObj.gaugeCustom)
⇒ g_gaugeOptionObj.gaugeXXXs.lifeBorders[譜面番号] が「x」以外であること。
- 譜面ヘッダー(difData)
⇒ g_headerObj.lifeBorders[譜面番号]が「x」以外であること。
- 基本設定(g_gaugeOptionObj)
⇒ g_gaugeOptionObj.typeSurvival[譜面番号] もしくは g_gaugeOptionObj.typeBorder[譜面番号] の値が「border」であること。（「survival」の場合はライフ制）

#### 5. 回復・ダメージ量の固定・変動条件
- カスタムゲージの場合
⇒ 譜面ヘッダー: customGaugeXの2要素目が「F」なら固定、「V」なら変動。
　 内部変数としては g_gaugeOptionObj.varCustom[譜面番号] で定義され、
　 「OFF」なら固定、「ON」なら変動。
- ライフ制ゲージ群の場合　※4. とは異なる。「Original, Light, Heavy, SuddenDeath」の1セット。
⇒ g_gaugeOptionObj.varSurvival[譜面番号]の値が「OFF」なら固定、「ON」なら変動。
- ノルマ制ゲージ群の場合　※4. とは異なる。「Normal, Easy, Hard, SuddenDeath」の1セット。
⇒ g_gaugeOptionObj.varBorder[譜面番号]の値が「OFF」なら固定、「ON」なら変動。
