### ISSUE TITLE
[不具合] Firefox 65：矢印などのマスク系画像が表示されない

### ISSUE THREAD

**Issue by cwtickle** [cwtickle/danoniplus#172]
**Describe the bug**
Firefox 65で、矢印などのマスク系画像が表示されない

**To Reproduce**
初期表示で、mask-imageを指定した画像フィルタが適用されず、表示されない。
※ローカル環境（オフライン）のみで発生します。

**Desktop (please complete the following information):**
 - OS: Windows 10 x64 (1809)
 - Browser [e.g. chrome, safari] ：Firefox
 - Version [e.g. 22] ：65

**Additional context**

**Comment by suzme** [comment]
about:configでstrict_origin_policyをfalseにすると表示されるようになりました。
[単純なHTMLとCSS](https://gist.github.com/suzme/56a875fac833e06fa9e70ddb8d8d17b3)でも再現したので、mask-imageに同一オリジンポリシーが適用されているようです。
background-imageなどでは問題ないので、よく分かりません…。

**Comment by cwtickle** [comment]
確認ありがとうございますー
やはりFirefoxの設定に関わるところでしたか。
この部分をjsのスクリプトで制御するのは何か違うような気がするので、
Wikiなどで設定変更などをアナウンスするようにした方が良いかもしれませんね。

**Comment by suzme** [comment]
スクリプトから変更することはできないはずです。
危険な設定なので、ローカルでは別のブラウザを使ってもらうほうがいいと思います。

**Comment by cwtickle** [comment]
ご意見ありがとうございます。
Firefox & ローカルの場合は警告文を出すなどの工夫が要りそうですね。

**Comment by cwtickle** [comment]
ver2.7.1にて、Firefox＆ローカル時に警告を出すように変えました。
当面この設定で進めることとし、このissueはクローズします。
