### ISSUE TITLE
フェードイン時にタイミングがずれる

### ISSUE THREAD

**Issue by suzme** [cwtickle/danoniplus#176]
**Describe the bug**
フェードイン時にタイミングがずれる場合があります。

**To Reproduce**
[eXtend the Rave](http://cw7.sakura.ne.jp/danoni/2009/0144_eXtendTheRave_short.html)をfadein 1%でプレイすると、0%と比べて譜面が2拍程度遅れます。
作品やfadein値によってずれ方が異なるようです。環境にも依るかもしれません。

**Desktop (please complete the following information):**
 - OS: WIndows 10
 - Browser: Chrome
 - Version: 72.0.3626.81

**Additional context**
Platebeatsでも似た問題がありましたし、Audio要素は正確なシークが出来ないのかもしれません。
高精度に制御できるらしい[Web Audio API](https://developer.mozilla.org/ja/docs/Web/API/Web_Audio_API)を試してみようと思っています。

**Comment by cwtickle** [comment]
この問題は難しいですね。
timeupdateを意図的に発生させてある程度ズレを無くすまでは行ったのですが、
それ以外は今のところ方法が見つかっていません・・・。

**Comment by cwtickle** [comment]
ver2.6.1 / ver1.15.2にてFadein1%の問題を修正しました。ありがとうございます。

**Comment by cwtickle** [comment]
#195 にてマージし、いくつかの作品で挙動を見てみました。
概ね解消されていますが、初回としばらく放置して再プレイした場合に、
たまに大きくずれるときがあります。

一例ですが、この作品のHard/Fadein74％で3回ほど確認しました。
環境はWindows 10 - 1809(x64)、Chrome72です。
http://cw7.sakura.ne.jp/danoni/2016/0277_PbrideRin.html

リトライすると直るので、以前と違って何度も起こるわけではなさそうです。

**Comment by suzme** [comment]
少し試してみましたがうまく再現しません…。
たまにということなので処理落ちの可能性がありそうですが、従来のバージョンでは起こらない挙動でしょうか？

**Comment by cwtickle** [comment]
従来のバージョンでもたまに発生していた記憶があります。
処理落ちには見えませんでした。
今回の変更で、確実にずれる部分については解消されているのでこれはこれで反映し、
こちらについては条件がはっきりするまでは様子見としたいと思います。

**Comment by cwtickle** [comment]
上記の問題はありますが、
元々のフェードイン時の話は一定の解決を見たと思いますので、クローズしておきます。
別の問題が発生した場合、再度New Issueからご指摘いただければと。
