### ISSUE TITLE
横一列17keyを作れるようにしたい

### ISSUE THREAD

**Issue by suzme** [cwtickle/danoniplus#181]
**Is your feature request related to a problem? Please describe.**
17keyのデフォルトがParaFla版のScroll=Alternate相当になっています。
ゲーム性が大きく異なるため、変更可能にしたいです。

**Describe the solution you'd like**
譜面ヘッダでPtnChangeのデフォルト値を変更可能にする。
両手用5key作品など、17key以外でも役に立つと思います。
~~~
|ptnDefault=0$1|
~~~
数値指定だとPtnChange周りの互換性が難しくなりそうなので、名前を付けたほうがいいかもしれません。
~~~
|ptnDefault=Alternate$1line|
~~~

**Describe alternatives you've considered**
17Akey、17Bkeyなど別キー扱いにする。

**Additional context**

**Comment by cwtickle** [comment]
ご意見ありがとうございます。
17keyに関しては、矢印サイズの関係もあり横サイズが長くなっている事情があります。
横幅を狭くしたりと工夫していますが、現状の拡張だと、ここまでが限界な気がします。

キーコンフィグパターンのデフォルト変更については、
今どのパターンがデフォルトになっているかを
プレイヤー側に知らせる必要があるかなと思っています。
単純に変更できるだけでなく、そういった視点も必要かなと。

現行の機能で済ませる場合、
独自キー作成の機能を使って17keyの設定をオーバーライドすることができますが、
あくまで暫定策だろうなと思っています。

**Comment by suzme** [comment]
> プレイヤー側に知らせる必要があるかなと思っています。

"17key(1line) / Normal"のようにしたいですがスペースが足りないですね。
Difficulty下の空白、KeyConfigボタン周辺、タイトル画面、あたりでしょうか。

> 独自キー作成の機能を使って17keyの設定をオーバーライドすることができます

とりあえず自分が作る際はこの方法でやろうと思います。
ありがとうございます。

**Comment by cwtickle** [comment]
ver3.3.0より、17keyのデフォルトが横一列になりました。
当初目的はクリアされているので、この件はクローズします。
