### ISSUE TITLE
矢印色をプレイヤーが変更できるようにしたい

### ISSUE THREAD

**Issue by suzme** [cwtickle/danoniplus#182]
**Is your feature request related to a problem? Please describe.**
12keyや横一列17keyなどでは色の重要性が高く、慣れていない配色パターンだとプレイが難しい。
変更可能にして少しでもとっつきやすくしたいです。

**Describe the solution you'd like**
オプションで矢印グループごとに色をいくつかの選択肢から選べるようにする。

**Describe alternatives you've considered**
オプションで配色をいくつかのパターンから選択できるようにする。

**Additional context**
氷矢色を矢印色に合わせるオプション(MFV2さんソースのFreezeColor)も欲しいです。
オプション画面のスペースは限られているので、置く場所は問題だと思います。

**Comment by cwtickle** [comment]
ご意見ありがとうございます。
色変更系は背景を使う場合でも起こる問題ですね。
どういった方向が良いかは具体的なイメージをつけて進めていきたいと思います。

オプション画面のスペースについては、
現在オプション画面のサブ画面（Display）が場所を大きく取っているため、
その部分の表示範囲を改良すれば、場所の確保はできそうだと思っています。

カラーパレットまで用意しようとすると、結構な手間になりそうですが・・・。
最初は数パターンから選択させるのが良いでしょうか。

**Comment by suzme** [comment]
キーコンフィグ画面の矢印をクリックで色変更、というのはどうでしょうか。
変更後の見た目が分かりやすく、スペースも説明1行追加だけで済みそうです。

キーコンフィグではないものをキーコンフィグに入れるのはあまりよくないかもしれませんが…。

**Comment by cwtickle** [comment]
案としては良いと思います。
キーコンフィグはキー設定(Key Settings)に名前を変えるなど方法はいくらでもありそうです。

キーコンフィグ画面の矢印は穴あき矢印なので、クリックさせようと思うとひと手間要りますね。
フリーズアローのように、矢印の塗部分の画像を利用する必要があるかと思います。

**Comment by cwtickle** [comment]
ver3.13.0にて、ConfigTypeの対面にColorTypeを作成し、
共通パターンを指定できるようにしました。

**Comment by suzme** [comment]
ありがとうございます！
キーコンフィグにボタンを置くのは分かりやすくていいですね。
目的が解決したのでcloseします。
