### ISSUE TITLE
[要望] スコア保存機能（FlashのSharedObject相当）の実装

### ISSUE THREAD

**Issue by cwtickle** [cwtickle/danoniplus#205]
**Is your feature request related to a problem? Please describe.**
ハイスコア機能の実装、及び周辺機能の実装

**Describe the solution you'd like**
LocalStorageもしくはIndexedDBによる実装を予定。
基本Key－Valueベースのため、被らない・煩雑にならない工夫が必要。
Keyが長くなりがちのため、長さとして問題ないかの検証も必要。

- Keyの決め方（案）
  1.  Dan★Oni(CW)として1つ共通のDBとする（LocalStorageでも使用可能か）。
[保存するデータの種類]-[キー数]-[譜面名]-[URL]　を結合したものをKeyとして扱う。

  2. Common, サイト別にそれぞれDBを持たせる。
また、データの種類ごとにテーブルを分ける。
[キー数]-[譜面名]-[URL]　を結合したものをKeyとして扱う。

  3. Common, サイト別にそれぞれDBを持たせる。
また、データの種類・URLごとにテーブルを分ける。
[キー数]-[譜面名]　を結合したものをKeyとして扱う。

**Additional context**
単にハイスコアを保存するだけでなく、
イベント毎の総プレイ数・総スコアを抽出できるなど、
データからイベントを作れるような、いろいろな使い方ができる設計にしたい。

**Comment by cwtickle** [comment]
Keyの重複を避けるため、譜面側やソースから指定させるのは避ける。
そのため、URLかそれを加工したものが良いと思うが、
全角文字が入ってきた場合はOKか？などは確認が必要。（譜面名に日本語が入ることがあるため）

**Comment by cwtickle** [comment]
この件は優先順をつけて、実装を予定しています。
ハイスコアなど、データの不整合が起こりやすい項目から着手するのは止め、
AdjustmentやVolumeの一時保存など、保存したデータを受け渡しするだけのところから
始めてみようと思っています。

**Comment by suzme** [comment]
> イベント毎の総プレイ数・総スコアを抽出できるなど、

サイト横断的に実現したい、ということでしょうか？
悪意のあるサイトからも読み書きされる可能性があり、
セキュリティやプライバシーの面でリスクが大きいように思います。
通常のスコア保存とは別にイベント用の機能として実装し、
読み書き可否をホワイトリスト等で対応したほうがいいのではないでしょうか。

**Comment by cwtickle** [comment]
そうですね、仰る通りだと思います。
調べた限りだと、異なるドメイン間のアクセスは制限が掛かっているようなので
最低でも同一サイト内の機能とイベント用の機能を分けることにはなると思っています。

この辺、まだ何もできてないのでどうにかしたいところではありますが。

**Comment by cwtickle** [comment]
LocalStorageで実装する方向で、ver4.1.0～4.6.1に掛けて実装しました。
下記、リセットボタンやON/OFFボタン含め一通りの実装が完了したので、クローズとします。
- キー別）リバース設定、キーコンフィグ設定
- 作品別）Adjustment、ハイスコア、音量設定
