### ISSUE TITLE
[要望] 譜面データのフォーマットチェック

### ISSUE THREAD

**Issue by cwtickle** [cwtickle/danoniplus#206]
**Is your feature request related to a problem? Please describe.**
特に手入れをする歌詞表示、背景表示データに多いが、現在はカンマとピリオドの打ち間違いがあっても、譜面をそのまま通してしまうため、画面が止まってしまう。
何らかのチェックを行い、読込画面でストップさせるような仕組みが欲しい。

**Describe the solution you'd like**
歌詞表示、背景表示のフレーム数、識別番号に対して数値以外が入ってきた場合、処理を止める。
（読込画面で止め、タイトルのような警告画面を表示）

**Describe alternatives you've considered**
もしくは、おかしいデータ以後のデータは読まずにメイン画面へ移行する。

**Additional context**

**Comment by cwtickle** [comment]
そもそもは歌詞表示や背景表示、色変化絡みに関するまともなエディターが無いことが問題なのですが…。
ソース側でも対策が取れたらいいかなということで。

外部ファイル化ができるようになって、特殊文字対応の敷居も下がりましたが（バッククォートを歌詞に使うケースはそんなにない）、英語歌詞となるとカンマを使うので、何かしらの対策がいると思いました。

**Comment by suzme** [comment]
カンマを使う歌詞は少なくないはずなので、別の書き方があってもいいかもしれませんね。
たとえばカンマ以外の区切り文字を使う、Frame,Positionの後カンマ+改行までをLyricsとみなす、など。
いずれにせよチェックも必要だとは思いますが。

**Comment by cwtickle** [comment]
都合の良い区切り文字ってなかなか無いんですよね。
パイプはもう使っているので、例えばスラッシュにすれば間違えないですね。
カンマ／ピリオドの一件はこの前に作品移行するときに自分がよくやったので提起しました。

歌詞(word_data)については背景(back_data)同様、
3つ1セット＋改行区切りで良いのかなと思っています。
読込パターンを2種類用意しておいて、区切り文字で判断、とかはありかもしれません。
それでも、その区切り文字を使う歌詞は出てくると思うので対策はいるんですけどね。

**Comment by cwtickle** [comment]
ver3.1.3にて、不正な歌詞データのスキップを実装しました。
すずめさんいつもありがとうございます m(_ _)m

**Comment by cwtickle** [comment]
歌詞データについて、行単位で取り込み可能となり
以前のようなエラーも頻発しなくなったので、一旦クローズとします。
