### ISSUE TITLE
[バグ] 長時間の楽曲を読み込む場合のエラー

### ISSUE THREAD

**Issue by cwtickle** [cwtickle/danoniplus#391]
**Describe the bug
（不具合の内容を記述してください）**
Vivaldiブラウザにおいて、長時間の楽曲を読み込むとPlease Waitで止まる。
楽曲をArrayBufferに格納している部分で発生している。

**To Reproduce
（不具合が発生した手順がわかれば、順を追って記述してください）**
1. 下記作品でPlay!を押したときに発生します。(Chromeでは再現せず)
http://www.omission0.com/danoni/175-186-kuina/

**Expected behavior
（不具合に対して、本来正しいと思われる動作を記述してください）**
通常同様にプレイ画面へ遷移する。

**Screenshots
（不具合時のスクリーンショットや具体的なコードがわかれば、リンク・記述をお願いします）**

**Desktop (please complete the following information):
（不具合が発生したOS・ブラウザのバージョンを記述してください）**
 - OS: [e.g. iOS] Windows 10 (1905)
 - Browser [e.g. chrome, safari] Vivaldi 
 - Version [e.g. 22] 2.6.1566.49 (32bit)

**Additional context
（その他、お気づきの点がありましたらご記入をお願いします）**
以下が参考になるかもしれません。
https://torisky.com/js%EF%BC%9Auncaught-in-promise-domexception%E3%82%A8%E3%83%A9%E3%83%BC%E3%81%A8settimeout/

**Comment by suzme** [comment]
64bit版では再現せず、32bit版では再現しました。
- OS: Windows 10 OS Version 1903 (Build 18362.356)
- Browser: Vivaldi
- Version: 2.7.1628.33 (Stable channel) (64-bit)
- Version: 2.7.1628.33 (Stable channel) (32-bit)

Chromeでも同様です。
- Browser: Chrome
- Version: 77.0.3865.75（Official Build） （64 ビット）
- Version: 77.0.3865.75（Official Build） （32 ビット）

おそらくmp3をデコードする際に必要なメモリ領域が32bitの限界より大きいのだと思います。

**Comment by cwtickle** [comment]
なるほど、メモリ不足が理由ならわかる気がしますね。
将来的には64bit版に移行する可能性が高いと思うので、この件についてはいったんクローズとします。
調査いただき、ありがとうございました m(_ _)m
