### ISSUE TITLE
[要望] LocalStorage(作品別)のキー統一

### ISSUE THREAD

**Issue by cwtickle** [cwtickle/danoniplus#480]
**Is your feature request related to a problem? Please describe.
（要望や問題点について記述して下さい）**
- 現状では、http/httpsで作品別のローカルストレージのキーが変わってしまう。
どちらにアクセスしても同じ設定が取得できるように設定を変更する。
※今後、httpsのサイトが増えていく可能性があるため、事前に手を打っておく。

**Describe the solution you'd like
（要望や問題点の解決方法を記述してください）**
- 現状はhttp始まりのサイトが多いため、http側に揃える。

**Describe alternatives you've considered
（上記の方法ができない場合、他の解決方法案があれば記述してください）**
- 特になし。

**Additional context
（その他、お気づきの点がありましたらご記入をお願いします）**

**Comment by suzme** [comment]
localStorageはオリジンごとに個別になるので、httpとhttpsでは共有できないみたいです
[同一オリジンポリシー - ウェブセキュリティ | MDN](https://developer.mozilla.org/ja/docs/Web/Security/Same-origin_policy)

**Comment by cwtickle** [comment]
そういえばそもそも別でしたね＼(^o^)／
解決のしようがないので、このIssueはクローズします、ありがとうございましたー
