### ISSUE TITLE
[要望] reverse時に歌詞等も上下逆の位置に表示する

### ISSUE THREAD

**Issue by satsukizzz** [cwtickle/danoniplus#747]
## 改善詳細 / Details of Improvement
- 歌詞のある曲で、reverseをかけた際には歌詞も上下逆の位置に表示する
## 期待する見せ方・挙動 / Expected Behavior
- reverse時にノートが歌詞とかぶって大変に見づらく、歌詞をOFFせざるを得ない。この点を解消したい。

## その他検討事項 / Other Considerations
- 現状、reverseしなければノートと歌詞がかぶることはない。

**Comment by cwtickle** [comment]
Issueありがとうございます！
この件ですが、想定しているより条件があり単純に反転できないため、条件を決めておく必要があります。

### 背景・マスクモーション (back_data, mask_data)
- 座標を直指定しているため上下反転はできません。

### 歌詞表示 (word_data)
- 次の条件を全て満たした場合のみ、歌詞表示の上下を反転します。
    - 上下スクロールを挟まないキーに限定（5key, 7key, 7ikey, 9A/9Bkeyなど）
    - リバース・スクロール拡張用の歌詞表示（wordRev_data / wordAlt_data）が設定されていない作品
    - SETTINGS 画面で Reverse：ON、Scroll：`---` (指定なし) を指定してプレイ開始した場合

**Comment by cwtickle** [comment]
Pull Requestにて対応案を上げてみました。
上記に加えて、歌詞表示が2段の場合も反転できないため、条件から除外します。

条件は絞られますが、実際のところ歌詞表示が1段以内のケースもそれなりにあるので、
反転した場合の利点はそれなりにあると思います。
